AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SalesPortalExportServerlessApp

  Sample SAM Template for SalesPortalExportServerlessApp

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    Tracing: Active

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
  ServerName:
    Type: String
    Description: Server with Sales Portal app
    Default: POL-SAGE-01
  SsmDocumentName:
    Type: String
    Description: SSM document to run Sales Portal app (to be dynamically created)
    Default: SalesPortalExportRunDocument

Conditions:
  IsTestOnlyResource:
    !Equals [ !Ref Environment, dev ]

Resources:
  SalesPortalExportAppStateMachineEventRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SalesPortalExportAppStateMachineEventPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  - !Sub "arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:SalesPortalExportAppStateMachineErrorTopic_${Environment}"
      RoleName: !Sub SalesPortalExportAppStateMachineEventRole_${Environment}
  SalesPortalExportAppStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SalesPortalExportAppStateMachinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutLogEvents
                  - logs:PutDestination
                  - logs:PutDestinationPolicy
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                Resource: '*'
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: '*'
      RoleName: !Sub SalesPortalExportAppStateMachineRole_${Environment}
  SalesPortalExportAppStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub SalesPortalExportAppStateMachine_${Environment}
      DefinitionUri: statemachine/sales_portal_export_serverless.asl.json
      Type: EXPRESS
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt SalesPortalExportAppStateMachineLogGroup.Arn
        IncludeExecutionData: true
        Level: ALL
      DefinitionSubstitutions:
        LambdaRunCheckSsmJobArn: !GetAtt SalesPortalExportAppLambdaRunCheckFunction.Arn
      Role: !GetAtt SalesPortalExportAppStateMachineRole.Arn
  SalesPortalExportAppStateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/state_machine/SalesPortalExportAppStateMachineLogGroup_${Environment}
      RetentionInDays: 7
  SalesPortalExportAppStateMachineFailureEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub SalesPortalExportAppStateMachineFailureEventRule_${Environment}
      Description: "Send SNS alert upon SalesPortalExportAppStateMachine Failure"
      EventPattern:
        source:
          - aws.states
        detail-type:
          - Step Functions Execution Status Change
        detail:
          status:
            - FAILED
            - ABORTED
            - TIMED_OUT
          stateMachineArn:
            - !Ref SalesPortalExportAppStateMachine
      Targets:
        - Arn: !Ref SalesPortalExportAppStateMachineErrorTopic
          Id: !Sub SalesPortalExportAppStateMachineErrorTopic_${Environment}
  SalesPortalExportAppStateMachineErrorTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub SalesPortalExportAppStateMachineErrorTopic_${Environment}
      Subscription:
        - Endpoint: itadmin@polanerselections.com
          Protocol: email
  SalesPortalExportAppStateMachineErrorTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Sid: AllowPublishToTopic
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: 'sns:Publish'
            Resource:
              - !Ref SalesPortalExportAppStateMachineErrorTopic
      Topics:
        - !Ref SalesPortalExportAppStateMachineErrorTopic
  SalesPortalExportAppLambdaRunCheckFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SalesPortalExportAppLambdaRunCheckFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:SendCommand
                  - ssm:ListCommands
                Resource: '*'
      RoleName:
        !Sub SalesPortalExportAppLambdaRunCheckFunctionRole_${Environment}

  SalesPortalExportAppLambdaRunCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/SalesPortalExportAppLambdaRunCheckFunction/
      Role: !GetAtt SalesPortalExportAppLambdaRunCheckFunctionRole.Arn
      FunctionName: !Sub SalesPortalExportAppLambdaRunCheckFunction_${Environment}
      Environment:
        Variables:
          SSM_DOCUMENT_NAME: !Ref SalesPortalExportAppSsmDocument
          SERVER_NAME: !Ref ServerName
      Handler: app.lambda_handler
      Runtime: python3.11
      LoggingConfig:
        LogGroup: !Ref SalesPortalExportAppLambdaRunCheckFunctionLogGroup
      Architectures:
        - x86_64
  SalesPortalExportAppLambdaRunCheckFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/SalesPortalExportAppLambdaRunCheckFunctionLogGroup_${Environment}
      RetentionInDays: 7

  SalesPortalExportAppSsmDocument:
      Type: AWS::SSM::Document
      Properties:
        Content:
          schemaVersion: '2.2'
          description: 'Runs Powershell Script to execute SalesPortalExport app'
          parameters:
            executionTimeout:
              type: String
              description: (Optional) The time in seconds for a command to complete before it is considered to have failed. Default is 300 (5 minutes). Maximum is 28800 (8 hours).
              default: '300'
            workingDirectory:
              type: String
              description: (Optional) The path to the SalesPortalExport app on the instance.
              default: 'D:\BoiApps\SalesPortalExport'
            salesOrderNumber:
              type: String
              description: (Required) Specify the Sales Order Number to import
              default: ''
            commands:
              type: String
              description: "(Required) Specify the SalesPortalExport app executable"
              default: 'D:\BoiApps\SalesPortalExport\SalesPortalExportIos.exe'
          mainSteps:
            - name: 'windows_script'
              action: 'aws:runPowerShellScript'
              precondition:
                StringEquals:
                  - platformType
                  - Windows
              inputs:
                  workingDirectory: '{{ workingDirectory }}'
                  timeoutSeconds: '{{ executionTimeout }}'
                  runCommand:
                    - '$ErrorActionPreference = \"Stop\"'
                    - '$jobDirectory = \"{{ workingDirectory }}\"'
                    - '{{ commands }} {{ salesOrderNumber }}'
                    - 'if (-not ($?)) { exit $LASTEXITCODE }'
        DocumentFormat: YAML
        DocumentType: Command
        Name: !Sub ${SsmDocumentName}_${Environment}

  SalesPortalExportAppFifoQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub SalesPortalExportAppFifoQueue_${Environment}.fifo
      FifoQueue: true
      SqsManagedSseEnabled: false
      ContentBasedDeduplication: true
      DeduplicationScope: messageGroup
      FifoThroughputLimit: perMessageGroupId
      VisibilityTimeout: 120
      MessageRetentionPeriod: 1209600 # 14 days
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SalesPortalExportAppFifoDeadLetterQueue.Arn
        maxReceiveCount: 3

  SalesPortalExportAppFifoDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      SqsManagedSseEnabled: false
      QueueName: !Sub SalesPortalExportAppFifoDeadLetterQueue_${Environment}.fifo
      MessageRetentionPeriod: 1209600

  SalesPortalExportAppFifoDeadLetterQueueAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub SalesPortalExportAppFifoDeadLetterQueueAlarm_${Environment}
      AlarmDescription: Alarm if dead-letter queue size exceeds threshold
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !GetAtt SalesPortalExportAppFifoDeadLetterQueue.QueueName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref SalesPortalExportAppFifoDeadLetterQueueAlarmTopic
      TreatMissingData: notBreaching

  SalesPortalExportAppFifoDeadLetterQueueAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub SalesPortalExportAppFifoDeadLetterQueueAlarm_${Environment}
      Subscription:
        - Endpoint: itadmin@polanerselections.com
          Protocol: email

  SalesPortalExportAppFifoQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "Allow all actions from root"
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: SQS:*
            Resource: !GetAtt SalesPortalExportAppFifoQueue.Arn
      Queues:
        - !Ref SalesPortalExportAppFifoQueue

  SalesPortalExportAppFifoQueueSendRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: SalesPortalExportAppFifoQueueSendPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt SalesPortalExportAppFifoQueue.Arn

  SalesPortalExportAppFifoQueuePipe:
    Type: AWS::Pipes::Pipe
    Properties:
      Name: !Sub SalesPortalExportAppFifoQueuePipe_${Environment}
      RoleArn: !GetAtt SalesPortalExportAppFifoQueuePipeRole.Arn
      Source: !GetAtt SalesPortalExportAppFifoQueue.Arn
      SourceParameters:
        SqsQueueParameters:
          BatchSize: 1
      Target: !Ref SalesPortalExportAppStateMachine
      TargetParameters:
        InputTemplate: |
          {
            "orderNumber": <$.body>
          }
        StepFunctionStateMachineParameters:
          InvocationType: REQUEST_RESPONSE
      LogConfiguration:
        Level: ERROR
        CloudwatchLogsLogDestination:
          LogGroupArn: !GetAtt SalesPortalExportAppFifoQueuePipeLogGroup.Arn

  SalesPortalExportAppFifoQueuePipeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: pipes.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PipesCloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt SalesPortalExportAppFifoQueuePipeLogGroup.Arn
        - PolicyName: PipesSQSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt SalesPortalExportAppFifoQueue.Arn
        - PolicyName: PipesStepFunctionsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref SalesPortalExportAppStateMachine

  SalesPortalExportAppFifoQueuePipeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/sqs/SalesPortalExportAppFifoQueuePipe_${Environment}
      RetentionInDays: 7


